from utils.db import get_connection

# Connect to your postgres DB
conn = get_connection()

# Open a cursor to perform database operations
with conn.cursor() as cur:
    # Execute a query
    cur.execute("""
        CREATE SCHEMA IF NOT EXISTS coingecko;

        CREATE TABLE IF NOT EXISTS coingecko.test_1 (
            code        char(16) CONSTRAINT firstkey PRIMARY KEY,
            symbol      varchar(40) NOT NULL UNIQUE,
            quote       varchar(40) NOT NULL UNIQUE,
            price       integer NOT NULL,
            m_cap       numeric NOT NULL,
            created_at  timestamp with time zone
        );

        CREATE TABLE IF NOT EXISTS coingecko.test_2 (
            did    integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name   varchar(40) NOT NULL CHECK (name <> '')
        );    
    """)

    cur.execute("""
        SELECT * FROM coingecko.test_1;
    """)

    records = cur.fetchall()
    print(records)